Repository jupyterlab/jupyter-chat, pull requests merged in 2024-06, with the labels that each got.

#46 Add screenshot to the README
  README.md
Labels: documentation

#47 Add the panel tracker to the chat factory token
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyterlab-collaborative-chat/schema/factory.json
  packages/jupyterlab-collaborative-chat/src/factory.ts
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/token.ts
  packages/jupyterlab-collaborative-chat/src/widget.tsx
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
Labels: enhancement

#48 Depend on `pydantic` directly instead of `langchain`
  packages/jupyterlab-ws-chat/jupyterlab_ws_chat/handlers.py
  packages/jupyterlab-ws-chat/jupyterlab_ws_chat/models.py
  packages/jupyterlab-ws-chat/pyproject.toml
Labels: maintenance

#43 Notifications for unread messages
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyter-chat/src/widgets/chat-widget.tsx
  packages/jupyter-chat/style/chat.css
  packages/jupyterlab-collaborative-chat/package.json
  packages/jupyterlab-collaborative-chat/src/factory.ts
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/widget.tsx
  packages/jupyterlab-collaborative-chat/style/base.css
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts-snapshots/navigation-bottom-linux.png
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts-snapshots/navigation-bottom-unread-linux.png
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts-snapshots/navigation-top-linux.png
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts-snapshots/tab-with-unread-linux.png
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts-snapshots/tab-without-unread-linux.png
  packages/jupyterlab-ws-chat/schema/chat.json
  packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts
  packages/jupyterlab-ws-chat/src/index.ts
  yarn.lock
Labels: enhancement

#55 Use the Chat.IOptions as option for the Widget and Sidebar
  packages/jupyter-chat/src/widgets/chat-sidebar.tsx
  packages/jupyter-chat/src/widgets/chat-widget.tsx
  packages/jupyterlab-collaborative-chat/src/factory.ts
  packages/jupyterlab-ws-chat/src/index.ts
Labels: maintenance

#54 Add metadata to ychat, id to model and store last unread in localStorage
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/model.ts
  packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
  packages/jupyterlab-collaborative-chat/src/model.ts
  packages/jupyterlab-collaborative-chat/src/ychat.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
  packages/jupyterlab-ws-chat/src/handlers/websocket-handler.ts
Labels: enhancement

#56 Buttons to mark chat as read
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/scroll-container.tsx
  packages/jupyter-chat/src/icons.ts
  packages/jupyter-chat/style/icons/read.svg
  packages/jupyterlab-collaborative-chat/schema/chat-panel.json
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/token.ts
  packages/jupyterlab-collaborative-chat/src/widget.tsx
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
Labels: enhancement, collaborative extension

#59 Prevent dependabot from using yarn 4
  package.json
  packages/jupyterlab-collaborative-chat/ui-tests/package.json
  packages/jupyterlab-ws-chat/ui-tests/package.json
Labels: maintenance
