Repository jupyterlab/jupyter-chat, pull requests merged in 2024-07, with the labels that each got.

#60 Fix the initialization of the messages component
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
Labels: bug

#57 Autocomplete commands
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/index.ts
  packages/jupyter-chat/src/registry.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyterlab-collaborative-chat/src/factory.ts
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/widget.tsx
  packages/jupyterlab-collaborative-chat/ui-tests/tests/autocompletion.spec.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
  packages/jupyterlab-ws-chat/src/index.ts
Labels: enhancement, collaborative extension, @jupyter/chat, websocket extension

#62 Fix bump version
  package.json
  packages/jupyter-chat/package.json
  packages/jupyterlab-collaborative-chat/package.json
  packages/jupyterlab-ws-chat/package.json
  packages/jupyterlab-ws-chat/ui-tests/package.json
  scripts/bump_version.py
Labels: maintenance

#65 Updated integration tests workflow
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#66 Update to jupyterlab 4.2.x
  packages/jupyter-chat/package.json
  packages/jupyterlab-collaborative-chat/package.json
  packages/jupyterlab-collaborative-chat/pyproject.toml
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/model.ts
  packages/jupyterlab-collaborative-chat/src/ychat.ts
  packages/jupyterlab-ws-chat/package.json
  yarn.lock
Labels: maintenance

#68 Add a configChanged signal to the model
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/model.ts
Labels: enhancement, @jupyter/chat
