Repository jupyterlab/jupyter-chat, pull requests merged in 2024-12, with the labels that each got.

#108 Rename server config file after renaming the extension
  python/jupyterlab-chat/jupyter-config/server-config/jupyterlab_chat.json
Labels: maintenance

#111 Fix rendering of code blocks in JupyterLab>= 4.3.0
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/style/chat.css
Labels: bug, @jupyter/chat

#127 Add the video of failing tests in playwright report
  ui-tests/playwright.config.js
  ui-tests/tests/commands.spec.ts-snapshots/launcher-tile-linux.png
  ui-tests/tests/notifications.spec.ts-snapshots/tab-with-unread-linux.png
  ui-tests/tests/notifications.spec.ts-snapshots/tab-without-unread-linux.png
  ui-tests/tests/ui-config.spec.ts-snapshots/not-stacked-messages-linux.png
  ui-tests/tests/ui-config.spec.ts-snapshots/stacked-messages-linux.png
  ui-tests/tests/unread.spec.ts-snapshots/navigation-bottom-linux.png
  ui-tests/tests/unread.spec.ts-snapshots/navigation-bottom-unread-linux.png
Labels: maintenance

#126 Prevent sending empty message
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/input/cancel-button.tsx
Labels: bug, @jupyter/chat

#125 Remove need for message index in YChat API methods
  python/jupyterlab-chat/jupyterlab_chat/models.py
  python/jupyterlab-chat/jupyterlab_chat/tests/test_ychat.py
  python/jupyterlab-chat/jupyterlab_chat/ychat.py
Labels: enhancement, chat extension

#94 Upgrade to Jupyter Collaboration 3
  packages/jupyterlab-chat/package.json
  packages/jupyterlab-chat/src/widget.tsx
  packages/jupyterlab-chat/src/ychat.ts
  python/jupyterlab-chat/package.json
  python/jupyterlab-chat/pyproject.toml
  python/jupyterlab-chat/src/index.ts
  yarn.lock
Labels: maintenance

#129 Fix math rendering using Latex delimiters
  packages/jupyter-chat/src/components/rendermime-markdown.tsx
Labels: bug

#123 Improve (and fix) unread messages and navigation
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/rendermime-markdown.tsx
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyterlab-chat/src/model.ts
  ui-tests/tests/notifications.spec.ts
  ui-tests/tests/test-utils.ts
  ui-tests/tests/unread.spec.ts
  ui-tests/tests/unread.spec.ts-snapshots/navigation-top-linux.png
  yarn.lock
Labels: bug, @jupyter/chat, chat extension

#132 Export components from @jupyter/chat
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/code-blocks/index.ts
  packages/jupyter-chat/src/components/index.ts
  packages/jupyter-chat/src/components/input/index.ts
  packages/jupyter-chat/src/components/markdown-renderer.tsx
  packages/jupyter-chat/src/components/mui-extras/index.ts
  packages/jupyter-chat/src/components/mui-extras/stacking-alert.tsx
  packages/jupyter-chat/src/index.ts
  packages/jupyter-chat/style/chat.css
  ui-tests/tests/chat-file.spec.ts
  ui-tests/tests/message-toolbar.spec.ts
  ui-tests/tests/send-message.spec.ts
  ui-tests/tests/test-utils.ts
Labels: maintenance

#136 Fix support for Python 3.9
  .github/workflows/build.yml
  python/jupyterlab-chat/jupyterlab_chat/models.py
Labels: bug
