Repository jupyterlab/jupyter-chat, pull requests merged in 2024-08, with the labels that each got.

#67 Code toolbar
  .github/workflows/build.yml
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/active-cell-manager.ts
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-chat/src/components/code-blocks/copy-button.tsx
  packages/jupyter-chat/src/components/copy-button.tsx
  packages/jupyter-chat/src/components/mui-extras/contrasting-tooltip.tsx
  packages/jupyter-chat/src/components/mui-extras/tooltipped-icon-button.tsx
  packages/jupyter-chat/src/components/rendermime-markdown.tsx
  packages/jupyter-chat/src/icons.ts
  packages/jupyter-chat/src/index.ts
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyter-chat/style/icons/replace-cell.svg
  packages/jupyterlab-collaborative-chat/package.json
  packages/jupyterlab-collaborative-chat/schema/factory.json
  packages/jupyterlab-collaborative-chat/src/factory.ts
  packages/jupyterlab-collaborative-chat/src/index.ts
  packages/jupyterlab-collaborative-chat/src/token.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/autocompletion.spec.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/code-toolbar.spec.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/jupyterlab_collaborative_chat.spec.ts
  packages/jupyterlab-collaborative-chat/ui-tests/tests/test-utils.ts
  packages/jupyterlab-ws-chat/package.json
  packages/jupyterlab-ws-chat/schema/chat.json
  packages/jupyterlab-ws-chat/src/index.ts
  yarn.lock
Labels: enhancement, collaborative extension, @jupyter/chat

#69 Improve ychat class on server side
  packages/jupyterlab-collaborative-chat/jupyterlab_collaborative_chat/ychat.py
  packages/jupyterlab-ws-chat/jupyterlab_ws_chat/models.py
Labels: enhancement

#74 Fix ReadTheDocs
  .readthedocs.yaml
  docs/requirements.txt
  pyproject.toml
Labels: documentation
