Repository jupyterlab/jupyter-chat, pull requests merged in 2025-03, with the labels that each got.

#171 Add new `InputModel` class for managing input state
  docs/jupyter-chat-example/src/index.ts
  packages/jupyter-chat/src/chat-commands/registry.ts
  packages/jupyter-chat/src/chat-commands/types.ts
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/components/input/send-button.tsx
  packages/jupyter-chat/src/components/input/use-chat-commands.tsx
  packages/jupyter-chat/src/components/input/utils.ts
  packages/jupyter-chat/src/index.ts
  packages/jupyter-chat/src/input-model.ts
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/widgets/chat-widget.tsx
  packages/jupyterlab-chat/src/model.ts
  python/jupyterlab-chat/src/chat-commands/providers/emoji.ts
  python/jupyterlab-chat/src/index.ts
Labels: enhancement

#187 Remove old autocomplete registry
  docs/source/developers/developing_extensions/extension-providing-chat.md
  docs/source/developers/developing_extensions/using-chat-extension.md
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/registry.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyterlab-chat/src/factory.ts
  packages/jupyterlab-chat/src/widget.tsx
  python/jupyterlab-chat/src/index.ts
Labels: maintenance

#188 Move the CSS rules of chat commands in @jupyter/chat
  packages/jupyter-chat/style/chat.css
  packages/jupyterlab-chat/style/base.css
Labels: bug

#192 Disable the copy button in insecure contexts
  packages/jupyter-chat/src/components/code-blocks/copy-button.tsx
Labels: enhancement

#195 Add a clearMessages() method in ChatModel
  packages/jupyter-chat/src/model.ts
  packages/jupyterlab-chat/src/model.ts
Labels: enhancement

#191 Fix the trailing hyphen in completion without description
  packages/jupyter-chat/src/components/input/use-chat-commands.tsx
Labels: bug
