Repository jupyterlab/jupyter-chat, pull requests merged in 2025-02, with the labels that each got.

#152 Update to `actions/upload-artifact@v4` and `actions/download-artifact@v4`
  .github/workflows/build.yml
  .github/workflows/check-release.yml
Labels: maintenance

#150 Improve the test execution
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/license-header.yml
  .github/workflows/ui-tests.yml
  python/jupyterlab-chat/jupyterlab_chat/ychat.py
Labels: maintenance

#142 Lint the whole project instead of individual packages
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update-integration-tests.yml
  CHANGELOG.md
  README.md
  binder/environment.yml
  docs/source/developers/contributing/index.md
  docs/source/developers/contributing/jupyterlab-chat-extension.md
  docs/source/developers/developing_extensions/extension-providing-chat.md
  docs/source/developers/developing_extensions/using-chat-extension.md
  docs/source/index.md
  docs/source/users/index.md
  package.json
  packages/jupyter-chat/package.json
  packages/jupyter-chat/style/chat.css
  packages/jupyterlab-chat/package.json
  python/jupyterlab-chat/.copier-answers.yml
  python/jupyterlab-chat/package.json
  ui-tests/tests/notebook-application.spec.ts
  ui-tests/tests/test-utils.ts
  yarn.lock
Labels: maintenance

#141 Move the Chat card in the 'Other' section of the launcher
  python/jupyterlab-chat/src/index.ts
  ui-tests/tests/commands.spec.ts
  ui-tests/tests/commands.spec.ts-snapshots/launcher-tile-linux.png
Labels: enhancement

#151 Add `Untitled*.ipynb` and `*.chat` to the `.gitignore`
  .gitignore
Labels: maintenance

#146 Adds side panel widgets to the tracker
  packages/jupyter-chat/src/widgets/chat-widget.tsx
  packages/jupyterlab-chat/src/token.ts
  packages/jupyterlab-chat/src/widget.tsx
  python/jupyterlab-chat/src/index.ts
  ui-tests/tests/commands.spec.ts
  ui-tests/tests/general.spec.ts
  ui-tests/tests/side-panel.spec.ts
  ui-tests/tests/test-utils.ts
Labels: enhancement, chat extension

#158 Allow use of up and down arrow in chat input
  packages/jupyter-chat/src/components/chat-input.tsx
Labels: bug

#160 Fix disabled code toolbar buttons
  packages/jupyter-chat/src/active-cell-manager.ts
  packages/jupyter-chat/style/icons/include-selection.svg
  packages/jupyter-chat/style/icons/read.svg
  packages/jupyter-chat/style/icons/replace-cell.svg
Labels: bug

#162 Lite deployment in doc
  .gitignore
  .readthedocs.yaml
  docs/jupyter-chat-example/README.md
  docs/jupyter-chat-example/install.json
  docs/jupyter-chat-example/jupyter_chat_example/__init__.py
  docs/jupyter-chat-example/package.json
  docs/jupyter-chat-example/pyproject.toml
  docs/jupyter-chat-example/schema/plugin.json
  docs/jupyter-chat-example/src/index.ts
  docs/jupyter-chat-example/style/base.css
  docs/jupyter-chat-example/style/index.css
  docs/jupyter-chat-example/style/index.js
  docs/jupyter-chat-example/tsconfig.json
  docs/requirements.txt
  docs/source/README.ipynb
  docs/source/_static/css/custom.css
  docs/source/conf.py
  docs/source/index.md
  package.json
  yarn.lock
Labels: documentation

#148 Implement message attachments
  docs/jupyter-chat-example/src/index.ts
  docs/source/README.ipynb
  docs/source/developers/developing_extensions/extension-providing-chat.md
  docs/source/users/index.md
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/components/attachments.tsx
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/components/input/attach-button.tsx
  packages/jupyter-chat/src/components/input/cancel-button.tsx
  packages/jupyter-chat/src/components/input/index.ts
  packages/jupyter-chat/src/context.ts
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/registry.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyter-chat/style/chat.css
  packages/jupyterlab-chat/package.json
  packages/jupyterlab-chat/src/factory.ts
  packages/jupyterlab-chat/src/model.ts
  packages/jupyterlab-chat/src/widget.tsx
  packages/jupyterlab-chat/src/ychat.ts
  python/jupyterlab-chat/jupyterlab_chat/models.py
  python/jupyterlab-chat/jupyterlab_chat/ychat.py
  python/jupyterlab-chat/package.json
  python/jupyterlab-chat/src/index.ts
  ui-tests/tests/attachments.spec.ts
  ui-tests/tests/notifications.spec.ts
  ui-tests/tests/test-utils.ts
  ui-tests/tests/unread.spec.ts-snapshots/navigation-top-linux.png
  yarn.lock
Labels: enhancement, @jupyter/chat, chat extension

#185 Add icons & descriptions to chat commands menu
  packages/jupyter-chat/src/chat-commands/types.ts
  packages/jupyter-chat/src/components/input/use-chat-commands.tsx
  packages/jupyterlab-chat/style/base.css
  python/jupyterlab-chat/src/chat-commands/providers/emoji.ts
Labels: enhancement
