Repository jupyterlab/jupyter-chat, pull requests merged in 2025-06, with the labels that each got.

#208 Display user writing notification when editing a message
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/input-model.ts
  packages/jupyter-chat/src/model.ts
  packages/jupyterlab-chat/src/model.ts
  ui-tests/tests/ui-config.spec.ts
  yarn.lock
Labels: enhancement

#227 Upgrade to Jupyter Collaboration 4
  packages/jupyter-chat/jest.config.js
  packages/jupyter-chat/jest.setup.js
  packages/jupyterlab-chat-extension/package.json
  packages/jupyterlab-chat-extension/src/index.ts
  packages/jupyterlab-chat/package.json
  packages/jupyterlab-chat/src/factory.ts
  packages/jupyterlab-chat/src/widget.tsx
  python/jupyterlab-chat/pyproject.toml
  yarn.lock
Labels: enhancement

#226 Code highlight in message
  packages/jupyter-chat/package.json
  packages/jupyter-chat/src/active-cell-manager.ts
  packages/jupyter-chat/src/components/input/buttons/send-button.tsx
  packages/jupyter-chat/src/selection-watcher.ts
  packages/jupyterlab-chat-extension/package.json
  packages/jupyterlab-chat-extension/src/index.ts
  ui-tests/tests/send-message.spec.ts
  yarn.lock
Labels: bug

#242 Fix v0.14.0 bugs
  docs/jupyter-chat-example/src/index.ts
  packages/jupyter-chat/src/components/input/chat-input.tsx
  packages/jupyter-chat/src/components/input/use-chat-commands.tsx
  packages/jupyter-chat/src/input-model.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyter-chat/src/utils.ts
  packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
  packages/jupyterlab-chat/src/model.ts
  packages/jupyterlab-chat/src/ychat.ts
  python/jupyterlab-chat/jupyterlab_chat/models.py
  python/jupyterlab-chat/jupyterlab_chat/tests/test_ychat.py
Labels: bug

#246 Make `user.mention_name` optional in frontend
  packages/jupyter-chat/src/types.ts
  packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
  packages/jupyterlab-chat/src/model.ts
Labels: maintenance
