Repository jupyterlab/jupyter-chat, pull requests merged in 2025-04, with the labels that each got.

#200 Fix the attachments on message edition and on python Message model
  packages/jupyterlab-chat/src/model.ts
  python/jupyterlab-chat/jupyterlab_chat/models.py
Labels: bug

#196 Move jupyterlab-chat-extension to packages directory
  .github/workflows/build.yml
  .github/workflows/ui-tests.yml
  .github/workflows/update-integration-tests.yml
  .gitignore
  .licenserc.yaml
  docs/source/developers/contributing/jupyterlab-chat-extension.md
  package.json
  packages/jupyterlab-chat-extension/package.json
  packages/jupyterlab-chat-extension/schema/chat-panel.json
  packages/jupyterlab-chat-extension/schema/commands.json
  packages/jupyterlab-chat-extension/schema/factory.json
  packages/jupyterlab-chat-extension/src/chat-commands/plugins.ts
  packages/jupyterlab-chat-extension/src/chat-commands/providers/emoji.ts
  packages/jupyterlab-chat-extension/src/index.ts
  packages/jupyterlab-chat-extension/style/base.css
  packages/jupyterlab-chat-extension/style/index.css
  packages/jupyterlab-chat-extension/style/index.js
  packages/jupyterlab-chat-extension/tsconfig.json
  python/jupyterlab-chat/jupyterlab_chat/_version.py
  python/jupyterlab-chat/pyproject.toml
  scripts/bump_version.py
  scripts/dev_install.py
  scripts/dev_install.sh
  yarn.lock
Labels: maintenance

#205 Fix the wrong version of python package
  python/jupyterlab-chat/jupyterlab_chat/_version.py
Labels: maintenance

#206 Fix the toolbar registry for main area chat
  packages/jupyterlab-chat/src/factory.ts
Labels: bug

#190 Mention users in messages (using @)
  docs/jupyter-chat-example/src/index.ts
  packages/jupyter-chat/src/__tests__/mocks.ts
  packages/jupyter-chat/src/__tests__/model.spec.ts
  packages/jupyter-chat/src/__tests__/widgets.spec.ts
  packages/jupyter-chat/src/chat-commands/types.ts
  packages/jupyter-chat/src/components/chat-input.tsx
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/input/use-chat-commands.tsx
  packages/jupyter-chat/src/index.ts
  packages/jupyter-chat/src/input-model.ts
  packages/jupyter-chat/src/model.ts
  packages/jupyter-chat/src/types.ts
  packages/jupyter-chat/src/utils.ts
  packages/jupyter-chat/style/chat.css
  packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
  packages/jupyterlab-chat-extension/src/index.ts
  packages/jupyterlab-chat/src/model.ts
  packages/jupyterlab-chat/src/ychat.ts
  python/jupyterlab-chat/jupyterlab_chat/models.py
  ui-tests/tests/user-mention.spec.ts
Labels: enhancement

#207 Fix _version.py file version bump
  scripts/bump_version.py
Labels: maintenance

#211 Fix case-sensitivity in user mention commands
  packages/jupyterlab-chat-extension/src/chat-commands/providers/user-mention.tsx
  ui-tests/tests/user-mention.spec.ts
Labels: bug

#210 Add a message footer registry, to allow extensions to provides their footers
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/components/chat.tsx
  packages/jupyter-chat/src/components/messages/footer.tsx
  packages/jupyter-chat/src/footers/index.ts
  packages/jupyter-chat/src/footers/registry.ts
  packages/jupyter-chat/src/footers/types.ts
  packages/jupyter-chat/src/index.ts
  packages/jupyterlab-chat-extension/src/index.ts
  packages/jupyterlab-chat/src/factory.ts
  packages/jupyterlab-chat/src/widget.tsx
  ui-tests/tests/ui-config.spec.ts-snapshots/not-stacked-messages-linux.png
  ui-tests/tests/ui-config.spec.ts-snapshots/stacked-messages-linux.png
  ui-tests/tests/unread.spec.ts-snapshots/navigation-top-linux.png
Labels: enhancement

#214 Allow Users to delete messages if sender is a bot, add optional `bot` bool to user models
  packages/jupyter-chat/src/components/chat-messages.tsx
  packages/jupyter-chat/src/types.ts
  python/jupyterlab-chat/jupyterlab_chat/models.py
Labels: enhancement
